### ISSUE TITLE
"404 page not found" on Signing-up as a speaker with Github account

### ISSUE THREAD

**Issue by colares** [thedevconf/cfp-devoxx-tdc#1]
How to reproduce:

1. Visit: http://cfp-flp.thedevconf.com.br/home
1. Click on "Github" button below "Sign-up with one of your social profile in 5 seconds. No password needed." (the link is http://cfp-flp.thedevconf.com.br/login/github)
1. It rises a "404 page not found" error (https://api.globalcode.com.br/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=3afbace5d9011c4510034174469f55f74f1ec773)

I hope it helps! :) Worked with Google Account

**Comment by kxavier** [comment]
Hi colares,

It was a URL configuration error for this instance. It was not an application issue. Here on GitHub we have the general source code for the application, but for each instance of the TDC there are particular configurations that have to be done by each production team.

You can use the support link for each event to send an email reporting these errors.

Thank you anyway!
