### ISSUE TITLE
Não é possível atualizar perfil

### ISSUE THREAD

**Issue by rafapg** [thedevconf/cfp-devoxx-tdc#3]
Quando criei meu perfil eu utilizei uma URL de foto que está quebrada.

Desde então venho tentando atualizar meu perfil para substituir a imagem e não consigo. Tudo ocorre corretamente mas a foto não é atualizada.

Posteriomente também tentei atualizar uma informação no cadastro e, apesar da mensagem de sucesso, a alteração não surtiu efeito.

URL do ambiente: 
http://cfp-rec.thedevconf.com.br/cfp/profile

**Comment by disouzaleo** [comment]
Olá @rafapg você consegue me dizer, qual foi o fluxo que você realizou ? 
Vou tentar reproduzir o bug e ver se consigo corrigir.

**Comment by jeffbicca** [comment]
Opa, @disouzaleo . Estava passando por essa situação da foto há uns dias atrás e agora aqui parece que resolveu.
Mas quando tento efetuar a atualização de país, estado e cidade, quando abro novamente o perfil para alteração, essas informações estão vindo zeradas.

**Comment by disouzaleo** [comment]
Oi @jeffbicca !
Consegue me dizer qual a edicao de evento você está acessando em que esse problema ocorre ? Recife ou POA

**Comment by jeffbicca** [comment]
> Oi @jeffbicca !
> Consegue me dizer qual a edicao de evento você está acessando em que esse problema ocorre ? Recife ou POA

É na edição POA, @disouzaleo .

**Comment by jeffbicca** [comment]
Feito, @disouzaleo ! Criei a issue #4 relatando esta situação.
Valeu!
