### ISSUE TITLE
Pedir nova senha, inscrever novo email

### ISSUE THREAD

**Issue by Rafaelfea** [thedevconf/cfp-devoxx-tdc#5]
quando vou para pedir nova senha ou inscrever novo email ocorre a página de erro a seguir

![WhatsApp Image 2020-01-13 at 20 30 18](https://user-images.githubusercontent.com/59885763/72363113-077f3d00-36d3-11ea-84e9-1765113bdb83.jpeg)

**Comment by ana-abrantes** [comment]
Questão já foi resolvida ;)
